# Generated by Django 3.0.5 on 2021-08-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=12, verbose_name='Rut')),
                ('dv', models.CharField(max_length=1, verbose_name='DV')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualizacion')),
            ],
        ),
    ]
